/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoTrabajamosRouteImport } from './routes/como-trabajamos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as SobreGarabsRouteImport } from './routes/sobre-garabs'
import { Route as TerminosDeServicioRouteImport } from './routes/terminos-de-servicio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoTrabajamosRoute = ComoTrabajamosRouteImport.update({
  id: '/como-trabajamos',
  path: '/como-trabajamos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreGarabsRoute = SobreGarabsRouteImport.update({
  id: '/sobre-garabs',
  path: '/sobre-garabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosDeServicioRoute = TerminosDeServicioRouteImport.update({
  id: '/terminos-de-servicio',
  path: '/terminos-de-servicio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-trabajamos': typeof ComoTrabajamosRoute
  '/contacto': typeof ContactoRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-garabs': typeof SobreGarabsRoute
  '/terminos-de-servicio': typeof TerminosDeServicioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-trabajamos': typeof ComoTrabajamosRoute
  '/contacto': typeof ContactoRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-garabs': typeof SobreGarabsRoute
  '/terminos-de-servicio': typeof TerminosDeServicioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-trabajamos': typeof ComoTrabajamosRoute
  '/contacto': typeof ContactoRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-garabs': typeof SobreGarabsRoute
  '/terminos-de-servicio': typeof TerminosDeServicioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-trabajamos'
    | '/contacto'
    | '/politica-de-privacidad'
    | '/preguntas-frecuentes'
    | '/servicios'
    | '/sobre-garabs'
    | '/terminos-de-servicio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-trabajamos'
    | '/contacto'
    | '/politica-de-privacidad'
    | '/preguntas-frecuentes'
    | '/servicios'
    | '/sobre-garabs'
    | '/terminos-de-servicio'
  id:
    | '__root__'
    | '/'
    | '/como-trabajamos'
    | '/contacto'
    | '/politica-de-privacidad'
    | '/preguntas-frecuentes'
    | '/servicios'
    | '/sobre-garabs'
    | '/terminos-de-servicio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoTrabajamosRoute: typeof ComoTrabajamosRoute
  ContactoRoute: typeof ContactoRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  ServiciosRoute: typeof ServiciosRoute
  SobreGarabsRoute: typeof SobreGarabsRoute
  TerminosDeServicioRoute: typeof TerminosDeServicioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-trabajamos': {
      id: '/como-trabajamos'
      path: '/como-trabajamos'
      fullPath: '/como-trabajamos'
      preLoaderRoute: typeof ComoTrabajamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-garabs': {
      id: '/sobre-garabs'
      path: '/sobre-garabs'
      fullPath: '/sobre-garabs'
      preLoaderRoute: typeof SobreGarabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos-de-servicio': {
      id: '/terminos-de-servicio'
      path: '/terminos-de-servicio'
      fullPath: '/terminos-de-servicio'
      preLoaderRoute: typeof TerminosDeServicioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoTrabajamosRoute: ComoTrabajamosRoute,
  ContactoRoute: ContactoRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  ServiciosRoute: ServiciosRoute,
  SobreGarabsRoute: SobreGarabsRoute,
  TerminosDeServicioRoute: TerminosDeServicioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
